language: node_js
node_js: stable

cache:
  directories:
    - node_modules
    - functions/node_modules

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: firebase
  project: stopmotion-med